# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('image_url', models.CharField(max_length=255, null=True)),
                ('bio', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.Pokemon'),
        ),
    ]
